PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>

SELECT ?tractor WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jonas#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jonas#farm-fbc84105-b376-4a91-9282-1bb4f3dbc8c9> as ?farm)
   ?farm a was:Farm.    
   ?farm was:contains ?tractor.
   ?tractor a was:Tractor.
 }
}